* Introduction
This is a simple string library that is more a proof of concept more than
anything else. It includes the in place small string optimization and you shoud
be able to return those stack objects fine by copy. the large string heap
version should also be fine by copy. I'm not happy with the api and keep trying
to simplify it.

* Allocations
Some of allocator arguments are optional for cases where you
know you wont need it, but for functions like reserve where it is always needed
(unless you are making unnecessary reserve calls) it is still required. I was
thinking of just making all allocator arguments optional but it doesn't make
sense in some cases but might make the api simplier.

* TODO
- [X] make allocator optional
- [ ] add basic string search
- [ ] add basic string splitting by iterator
- [ ] add substring spans and indexing
- [X] reserve, clear
- [ ] basic forward iterator
- [ ] push back, set, delete
- [X] heap to stack
- [ ] find, find iter
- [ ] compare, copy substr
- [ ] map iter
- [ ] replace
- [ ] realloc should first attempt to extend region
- [X] document
