* Introduction
This is a simple string library that is more a proof of concept more than
anything else. It includes the in place small string optimization and you shoud
be able to return those stack objects fine by copy. the large string heap
version should also be fine by copy. I'm not happy with the api and keep trying
to simplify it.

* Allocations
Some of allocator arguments are optional for cases where you
know you wont need it, but for functions like reserve where it is always needed
(unless you are making unnecessary reserve calls) it is still required. I was
thinking of just making all allocator arguments optional but it doesn't make
sense in some cases but might make the api simplier.

* Extend to small vec
It should be possible to use this for u8 numbers already if you just ignore the
word string all over the place. It should also be possible to wrap this in a
type function and have it use u16 or other, but it becomes much more limited and
I think there are better ways to do small vecs. Usually you don't need to spill
characteristics and you know if you will have large or small vectors at compile
time, and if you don't it is usually easier to manage than strings. I'd be more
include to just write a small vec implementation with no spillage.

* Usage without the union String indirection
Often you will now if you have a small or large string. for example, if you use
this as a hash key and know your key length. you can use SmallString and
LargeString directly if you want or you can still use String and call into
String.small or String.large if you already know. There is also some isSmall and
isLargeStr predicates to help with that. String.lowbyte is also there to help
determine the union type.

* TODO
- [X] make allocator optional
- [ ] add basic string search
- [ ] add basic string splitting by iterator
- [ ] add substring spans and indexing
- [X] reserve, clear
- [ ] basic forward iterator
- [ ] push back
- [ ] set
- [ ] delete, delete range
- [X] heap to stack
- [ ] find, find iter
- [ ] compare, copy substr
- [ ] map iter
- [ ] replace
- [ ] realloc should first attempt to extend region
- [X] document
